### ISSUE TITLE
Automatically set issue status to In Progress

### ISSUE THREAD

**Issue by fgrehm** [fernandokosh/redmine_time_tracker#10]
but only when starting to track time for _New_ or _Assigned to_.

What do you think?

**Comment by delaitre** [comment]
The problem is that issue statuses can be created/deleted by the redmine admin.
For example, the "In Progress" status does not necessarily exist, or this is not the one which should be set.

I think this should be configurable in the plugin settings.
Anyway, I think this is a good idea which follows the plugin idea: simplifying the user workflow.

**Comment by delaitre** [comment]
Just to let you know that I'm working on it. Don't know when it will be done though, I have plenty of work. Maybe should II push my current work on a separate branch.

**Comment by delaitre** [comment]
I've implemented the settings part for this feature in the 'auto_status_update'. This allows to manage a status transitions list to apply from the plugin configuration page.

Todo:
- Display a notification if a status used in a transition has been deleted.
- Apply the transition if needed when a time tracker is started.

**Comment by delaitre** [comment]
The feature is available in master.

**Comment by fgrehm** [comment]
Awesome! I'll try out later on :-)
