### ISSUE TITLE
User assigment on start

### ISSUE THREAD

**Issue by soeron** [fernandokosh/redmine_time_tracker#50]
In our team when we post issues we don't assign em at submit point.
It would be nice feature if you could implement some settings about assigning user to the issue when he starts a timer for it.

Currently patched time_trackers_controller.rb
@119 added

@issue.assigned_to_id = User.current.id

to assign user on starting timer

**Comment by delaitre** [comment]
The could be a good idea with a plugin setting to enable/disable the feature.
In our team, it is common for several guy to start a time tracker on the same issue (for example a global "design" or "meeting" feature). Thus changing the assignment each time would be weird.

However, the solution could be to assign a new user only if the issue is not yet assigned.

**Comment by soeron** [comment]
Sounds logical, and doubt it would be hard to implent.
Wonderful work on the plugin. Keep up the good work :)

**Comment by soeron** [comment]
Jeez >< sorry for the spam can't get used to the UI of github yet ;/
