### ISSUE TITLE
Ability to stop logging when ticket is closed

### ISSUE THREAD

**Issue by tvollstaedt** [fernandokosh/redmine_time_tracker#62]
This would be nice, especially when one closes ticket via scm. Currently, i start tracking, finish my work, stop tracking time and close the ticket via commit comment. It would be much more confortable if time tracking stops automatically with the auto close on commit. This would require to set activity before tracking starts.

I saw that you currently have not much time left for time_tracker anymore. I fully understand this, but have you considered to pass the project to someone else? There is even a pull request which is nine months old :-)

**Comment by delaitre** [comment]
This would make sense, but I'm really not a fan of the need to set the
activity before the start of the time tracking...

Regarding the maintenance and future development of the project, I'll be
very happy to pass the project to someone else for several reason:
- I don't have much free time for this project
- I'm a beginner in Ruby/RoR and, while I was happy to discover a new
  technology, I have no interest in digging into them further. Each time I
  rework a little bit on the project, I need to remember how this framework
  works!
- I started the project because I had a real need of it for my daily job.
  Since the plugin almost "do the job", it's hard to motivate me to polish it
  and add new features (especially because I'm a Ruby/RoR beginner). What I'm
  really missing is the multi-tracker feature (#61) but it needs some
  architectural changes in the code.

However, I don't know how to find someone! Maybe a mail on the
redmine/chili-project mailing list, or contacting directly the people who
have forked the project and already made some development.

For the pending pull request, I think I wanted to rewrite it in a more
generic manner to be "multi-tracker" ready...so I didn't merge it. However,
I could merge it and rework it later on, when multi-tracker will be ready.
