### ISSUE TITLE
Big buttons ?

### ISSUE THREAD

**Issue by kissgyorgy** [fernandokosh/redmine_time_tracker#65]
It's so hard to click on those small buttons!

**Comment by delaitre** [comment]
While a little bit small, I don't think I can make them bigger since they have the same size as the "header". As you are not clicking (I think...) so often on the buttons, I think it's better to have them nicely integrated (the current solution) rather than easier to use but uglier.

If you think of a better solution, feel free to re-open the issue!

**Comment by kissgyorgy** [comment]
Check out this chrome extension:
https://chrome.google.com/webstore/detail/mkpkclfhemlehfbeinbjnbjebbikgfpb
It's almost good, but not cross-browser solution and counter stops when you change page.

**Comment by delaitre** [comment]
So you want buttons on the issue page rather than the small ones on the
header?
This is what I've implemented first in my prototype but found it rather
hard to do as a redmine plugin. Moreover, I prefer having all the time
tracker information in the header...

To be noted that the time tracker actions are still available in the issue
context menu (right click on an issue in the "Issues" page). Maybe this can
help you.

As a side note, I didn't know that redmine extensions were available as
browser plugin rather than traditional redmine plugin. This allow each user
to have its plugins rather than "poluting" the redmine installation with
all of them. It needs however to develop one plugin per browser...
